try {
   let a = 0;
//    console.log(program)
   console.log("this code ran")
} catch (error) {
    console.log("this is an error")
    console.log(program)
}
finally {
    console.log("this will definitly run")
}